---
# handlers file for ansible-collectd

- name: Restart collectd
  service: name=collectd state=restarted

- name: Reload nginx
  service: name=nginx state=reloaded

- name: Reload apache
  service: name=apache2 state=reloaded

- name: Restart ntp
  service: name=ntp state=restarted
